In [1]:
from numpy import random
N = 500
d = 300
C = 5
W = random.rand(C,d)
wordvectors_list = [random.rand(d,1) for i in range(N)]
wordvectors_one_matrix = random.rand(d,N)

%timeit [W.dot(wordvectors_list[i]) for i in range(N)]
%timeit W.dot(wordvectors_one_matrix)

1.34 ms ± 115 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
103 µs ± 13.4 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [4]:
import numpy as np
A = np.array([[1,2],[3,4]])
print(A.shape)
B = A[:,np.newaxis,:]
print(B.shape)
B

(2, 2)
(2, 1, 2)


array([[[1, 2]],

       [[3, 4]]])

In [60]:
a = [[1,2,3],[3,4,5],[5,6,7]]
b = [[21,31,41],[41,51,61],[51,61,71]]
for i in range(3):
    print(np.stack((a,b),axis=i))

[[[ 1  2  3]
  [ 3  4  5]
  [ 5  6  7]]

 [[21 31 41]
  [41 51 61]
  [51 61 71]]]
[[[ 1  2  3]
  [21 31 41]]

 [[ 3  4  5]
  [41 51 61]]

 [[ 5  6  7]
  [51 61 71]]]
[[[ 1 21]
  [ 2 31]
  [ 3 41]]

 [[ 3 41]
  [ 4 51]
  [ 5 61]]

 [[ 5 51]
  [ 6 61]
  [ 7 71]]]


In [4]:
import numpy as np
a = np.array([1,2,3,4]).reshape(np.array)
np.sum(a,axis=0)

10

In [8]:
a = [[i for i in range(5)]]
b = [[i for i in range(5)]]
a+b            

[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]

In [15]:
np.array([2,3])**2

array([4, 9])